baseURL = 'https://sifa.game/'
languageCode = 'en-us'
title = 'SIFA'
theme = 'paper'
enableEmoji = true
comments = false
googleAnalytics = "G-4DGYDNQTSQ"

[params]
  description = 'A Web3 Game'
  logo = '/sifa.svg'

  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  github = 'sifagame'                 # github.com/YOUR_GITHUB_ID
  twitter = 'sifagame'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

[menu]
  [[menu.main]]
    identifier = "testnet"
    name = "🧪 Testnet"
    url = "https://testnet.sifa.game"
    weight = 5
  [[menu.main]]
    identifier = "roadmap"
    name = "Roadmap"
    url = "/#roadmap"
    weight = 10
  [[menu.main]]
    identifier = "telegram"
    name = "Telegram"
    url = "https://t.me/SifaGameOfficial"
    weight = 20